### ISSUE TITLE
Newtonsoft.Json.Linq.JArray' cannot be converted to type 'System.Collections.Generic.HashSet`1[Orleans.Streams.PubSubPublisherState]'.

### ISSUE THREAD

**Issue by amccool** [OrleansContrib/Orleans.StorageProvider.Redis#4] opened 2016-02-05 18:13 UTC
I'm getting occasionally failures using PubSubStore and streams

Exc level 0: Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message NewPlacement Request S172.18.124.92:11111:192315922*cli/916eb7ad@cdeb1280->S172.18.124.91:11111:192315927*grn/716E8E94/00917a8c+SMSProvider_ProvingGroundStreamNamespace@2b9109a6 #4[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:GetAllSubscriptions() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now. System.ArgumentException: Object of type 'Newtonsoft.Json.Linq.JArray' cannot be converted to type 'System.Collections.Generic.HashSet`1[Orleans.Streams.PubSubPublisherState]'.

at first look there appears to be data in the redis:
GrainReference=40628da454c29730b799065600917a8c06000000716e8e94+SMSProvider_ProvingGroundStreamNamespace

{
	"Producers": [{
		"Stream": {
			"Guid": "54c29730-8da4-4062-8c7a-9100560699b7",
			"ProviderName": "SMSProvider",
			"Namespace": "ProvingGroundStreamNamespace"
		},
		"producerReference": {
			"GrainId": "4bb741b3bb9b2fc5b5d0dd2d95a65db60400000000000000",
			"ObserverId": "ea9e95e9-2a23-4c25-b504-35352a638417",
			"GenericArguments": ""
		},
		"Producer": {
			"GrainId": "4bb741b3bb9b2fc5b5d0dd2d95a65db60400000000000000",
			"ObserverId": "ea9e95e9-2a23-4c25-b504-35352a638417",
			"GenericArguments": ""
		}
	},
	{
		"Stream": {
			"Guid": "54c29730-8da4-4062-8c7a-9100560699b7",
			"ProviderName": "SMSProvider",
			"Namespace": "ProvingGroundStreamNamespace"
		},
		"producerReference": {
			"GrainId": "4face51f0b478c231bfa2ffd97031fa20400000000000000",
			"ObserverId": "ec03e62d-c6c4-4225-8336-02cd42f85ed5",
			"GenericArguments": ""
		},
		"Producer": {
			"GrainId": "4face51f0b478c231bfa2ffd97031fa20400000000000000",
			"ObserverId": "ec03e62d-c6c4-4225-8336-02cd42f85ed5",
			"GenericArguments": ""
		}
	},
	{
		"Stream": {
			"Guid": "54c29730-8da4-4062-8c7a-9100560699b7",
			"ProviderName": "SMSProvider",
			"Namespace": "ProvingGroundStreamNamespace"
		},
		"producerReference": {
			"GrainId": "47d5eda872f7ffa8218ab7edc4ef4d990400000000000000",
			"ObserverId": "fe9b44ea-8d70-4cb9-b207-ad0bd938731d",
			"GenericArguments": ""
		},
		"Producer": {
			"GrainId": "47d5eda872f7ffa8218ab7edc4ef4d990400000000000000",
			"ObserverId": "fe9b44ea-8d70-4cb9-b207-ad0bd938731d",
			"GenericArguments": ""
		}
	}],
	"Consumers": [{
		"SubscriptionId": {
			"Guid": "8f83c9f6-8154-4c72-8778-dc45e306c100"
		},
		"Stream": {
			"Guid": "54c29730-8da4-4062-8c7a-9100560699b7",
			"ProviderName": "SMSProvider",
			"Namespace": "ProvingGroundStreamNamespace"
		},
		"consumerReference": {
			"GrainId": "4c03cc653af97b91b6774b5bb124e4890400000000000000",
			"ObserverId": "ec4a471d-0925-4887-97af-e6eb8ac2dde4",
			"GenericArguments": ""
		},
		"filterWrapper": null,
		"state": 0,
		"Consumer": {
			"GrainId": "4c03cc653af97b91b6774b5bb124e4890400000000000000",
			"ObserverId": "ec4a471d-0925-4887-97af-e6eb8ac2dde4",
			"GenericArguments": ""
		},
		"Filter": null,
		"IsFaulted": false
	},
	{
		"SubscriptionId": {
			"Guid": "0356ae2a-f02a-4bf0-bb66-f3630bbf0324"
		},
		"Stream": {
			"Guid": "54c29730-8da4-4062-8c7a-9100560699b7",
			"ProviderName": "SMSProvider",
			"Namespace": "ProvingGroundStreamNamespace"
		},
		"consumerReference": {
			"GrainId": "4ba6ba7f381df37ede4a5c556a2231b50400000000000000",
			"ObserverId": "9006ceb8-5848-45e9-bfc1-666f08bdcda1",
			"GenericArguments": ""
		},
		"filterWrapper": null,
		"state": 0,
		"Consumer": {
			"GrainId": "4ba6ba7f381df37ede4a5c556a2231b50400000000000000",
			"ObserverId": "9006ceb8-5848-45e9-bfc1-666f08bdcda1",
			"GenericArguments": ""
		},
		"Filter": null,
		"IsFaulted": false
	},
	{
		"SubscriptionId": {
			"Guid": "baad2119-2b82-45df-860b-2f89b0237520"
		},
		"Stream": {
			"Guid": "54c29730-8da4-4062-8c7a-9100560699b7",
			"ProviderName": "SMSProvider",
			"Namespace": "ProvingGroundStreamNamespace"
		},
		"consumerReference": {
			"GrainId": "45df620b45579f6fc5cc151f1a907fa60400000000000000",
			"ObserverId": "998c8f28-cb63-4943-9460-38c1eb7bf8fc",
			"GenericArguments": ""
		},
		"filterWrapper": null,
		"state": 0,
		"Consumer": {
			"GrainId": "45df620b45579f6fc5cc151f1a907fa60400000000000000",
			"ObserverId": "998c8f28-cb63-4943-9460-38c1eb7bf8fc",
			"GenericArguments": ""
		},
		"Filter": null,
		"IsFaulted": false
	},
	{
		"SubscriptionId": {
			"Guid": "1c3ea63e-3d8b-4adc-840f-96c4c700b46e"
		},
		"Stream": {
			"Guid": "54c29730-8da4-4062-8c7a-9100560699b7",
			"ProviderName": "SMSProvider",
			"Namespace": "ProvingGroundStreamNamespace"
		},
		"consumerReference": {
			"GrainId": "4fe65043ebf3e9e2150d84f2eff1898d0400000000000000",
			"ObserverId": "38b0ac35-0258-4879-8d4b-cc33052ba485",
			"GenericArguments": ""
		},
		"filterWrapper": null,
		"state": 0,
		"Consumer": {
			"GrainId": "4fe65043ebf3e9e2150d84f2eff1898d0400000000000000",
			"ObserverId": "38b0ac35-0258-4879-8d4b-cc33052ba485",
			"GenericArguments": ""
		},
		"Filter": null,
		"IsFaulted": false
	}]
}

**Comment by gabikliot** [comment] 2016-02-06 01:17
Most probably the problem is that it does not configure the Json settings correctly.
Azure table provider and Azure Blob providers configure them differently.
https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs#L104

You can either just copy the settings from there, or better - use the same OrleansJsonSerializer.SerializerSettings. Its now internal, so you will need to open an issue on Orleans, there will be some discussions of how to expose unified Json settings (that also include serialization for internal Orleans classes). I do think it will be good to move towards unified Json settings configuration in Orleans in general.

**Comment by amccool** [comment] 2016-02-06 03:08
short term I suppose I could copy the same settings.

**Comment by gabikliot** [comment] 2016-02-06 04:02
Definitely good thing to try first.

**Comment by amccool** [comment] 2016-02-09 09:59
@gabikliot the json.net serializer was a no go per https://github.com/dotnet/orleans/issues/1269
I switched to the Orleans.Serialization.SerializationManager (binary, right?) and that appears to be working much better.

PR https://github.com/OrleansContrib/Orleans.StorageProvider.Redis/pull/5

question:  is the default for AzureTableStorage json or binary?

**Comment by richorama** [comment] 2016-02-09 10:07
@amccool table storage defaults to `Orleans.Serialization.SerializationManager` which is indeed binary.

**Comment by amccool** [comment] 2016-02-10 22:33
PR https://github.com/OrleansContrib/Orleans.StorageProvider.Redis/pull/5 allows for a binary serializer which alleviates the issue.

**Comment by richorama** [comment] 2016-02-11 10:00
closed by #5

**Closed by richorama** 2016-02-11 10:00 UTC
